export const COMPONENT_TYPES = {
  ANTD: 'Ант Дизайн',
  KSNM: 'KSNM UI',
  LOCAL: 'Локальные/нативные',
} as const;
export type ComponentType = (typeof COMPONENT_TYPES)[keyof typeof COMPONENT_TYPES];

// Явная типизация, чтобы не схлопывалось в Set<never>
export const INTRINSIC_HTML: Set<string> = new Set<string>([
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'base',
  'bdi',
  'bdo',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'cite',
  'code',
  'col',
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'label',
  'legend',
  'li',
  'link',
  'main',
  'map',
  'mark',
  'meta',
  'meter',
  'nav',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'script',
  'search',
  'section',
  'select',
  'slot',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'template',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
]);

export const INTERACTIVE_HTML: Set<string> = new Set<string>([
  'input',
  'select',
  'textarea',
  'button',
  'a',
  'option',
  'optgroup',
]);

export const isInteractiveIntrinsic = (tag: string): boolean => INTERACTIVE_HTML.has(tag);
export const isCamelCaseComponent = (name: string): boolean => /^(?:[A-Z][A-Za-z0-9]*)$/.test(name);
export const isRelativeModule = (spec: string): boolean => spec.startsWith('./') || spec.startsWith('../');
